# Dockerfile.base
FROM python:3.11-slim

# Set the default workdir
WORKDIR /app

#Environment
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1


#Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git curl ffmpeg libpq-dev libssl-dev libffi-dev libsndfile1 libmagic1 && \
    rm -rf /var/lib/apt/lists/*


# Install ML-heavy Python dependencies
COPY requirements-base.txt /app/requirements-base.txt
RUN pip install --no-cache-dir -r requirements-base.txt


