FROM mamacare-base AS mamacare-ui

WORKDIR /app

# Copy UI-specific dependencies
COPY ui/requirements-ui.txt .
RUN pip install --no-cache-dir -r requirements-ui.txt


# Copy UI code
COPY ui/ /app


# Expose Streamlit port
EXPOSE 8501

# Run Streamlit app

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
