FROM mamacare-base:latest AS mamacare-rag-backend

WORKDIR /app

# Copy backend-specific dependencies
COPY backend/requirements-backend.txt .

RUN pip install --no-cache-dir -r requirements-backend.txt

# Copy backend code
COPY backend/ /app/backend/
COPY docker/start-backend.sh  /app/docker/start-backend.sh

RUN chmod +x /app/docker/start-backend.sh

# Expose backend code
EXPOSE 8000


# Run FastAPI
CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
